[log]
    level_logfile = "DEBUG"
    level_stderr = "WARNING"
[gossip]
    port = 8700
[consensus]
    expected_shred_version = 35459
[tiles]
    [tiles.gossip]
        peer_ip_addr = "139.178.68.207"
        peer_port = 8001
        gossip_listen_port = 8700
    [tiles.repair]
        repair_intake_listen_port = 8701
        repair_serve_listen_port = 8702
    [tiles.replay]
        snapshot = "/home/lheeger/ledger/snapshot-268723793-3MJ6C9GLo3pLtHxCU9ZJgbawFFpZjc4c1kb4BBFoGJFE.tar.zst"
        incremental = "/home/lheeger/ledger/incremental-snapshot-268723793-268731014-9oPfcW5VWPQWwarRj9RMav1uRjtwgpGQb6KsVbyFYsnu.tar.zst"
    [tiles.store]
        snapshot_slot = 268731014
[development]
    topology = "firedancer"
